services:
  node:
    build: .
    container_name: corsofleuri
    volumes:
      - .:/usr/src/app 
    working_dir: /usr/src/app 
    ports:
      - "8082:8082"
    command: npm run dev 

  php:
    image: php:8.1-fpm
    container_name: php-fpm
    volumes:
      - ./html:/var/www/html
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./html:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8083:8083"
    depends_on:
      - php


  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_corsofleuri
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "2373:80"
    depends_on:
      - db

volumes:
  db_data:
