services:
  node:
    build: .
    container_name: corsofleuri
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "8082:8082"
    command: npm run dev

  php:
    image: php:8.1-fpm
    container_name: php-fpm
    volumes:
      - ./html:/var/www/html

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./html:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8083:8083"
    depends_on:
      - php

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_corsofleuri
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    ports:
      - "2373:80"
    depends_on:
      - db

volumes:
  db_data:
