services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-fpm
    volumes:
      - ./Back/app:/var/www/app
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./Back/app:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8083:80"
    depends_on:
      - php

  node-front:
    build:
      context: ./Front/src
      dockerfile: Dockerfile
    container_name: node-front
    volumes:
      - ./Front/src/:/usr/src/app
    working_dir: /usr/src/app
    command: npm start
    ports:
      - "8085:3000"
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8084:80"
    depends_on:
      - db

volumes:
  db_data:
